#!/usr/bin/env python3
"""
Shared timeline maths for the video pipeline.

Both assemble_video.py and gen_subtitles.py import this so the images and the
subtitles are derived from exactly the same numbers -- otherwise the subs
would drift out of sync with the visuals.

Each segment gets a slice of the narration audio proportional to its word
count, with a floor so very short segments still stay readable.

When edge-tts word-level timestamps are available (word_timings.json), the
timeline is built from actual audio timing instead of word-count approximation,
giving frame-perfect sync between audio and subtitle animation.
"""
import json
import re
import subprocess
from pathlib import Path

DEFAULT_MIN_DURATION = 1.2

# 100 ns units from Edge TTS metadata -> seconds
_TTS_TIME_TO_SEC = 10_000_000


def load_word_timings(video_dir: Path):
    """Load word_timings.json generated by tts_edge.py, or None."""
    path = video_dir / "word_timings.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    out = []
    for w in data:
        if w.get("type") == "WordBoundary":
            out.append({
                "text": w["text"],
                "start": w["offset"] / _TTS_TIME_TO_SEC,
                "end": (w["offset"] + w["duration"]) / _TTS_TIME_TO_SEC,
            })
    return out


def _normalise_word(w: str) -> str:
    return re.sub(r"[^\w]+", "", w).lower()


def match_words_to_timings(segments, word_timings):
    """Match segment words to TTS word timings.

    Returns a list of dicts, one per segment:
      {"words": [{"text": ..., "reveal": sec_from_seg_start}, ...],
       "start": float, "end": float, "duration": float}
    or None if matching fails.
    """
    seg_word_lists = [s["text"].split() for s in segments]
    flat_words = [w for words in seg_word_lists for w in words]
    flat_norm = [_normalise_word(w) for w in flat_words]

    timing_norm = [_normalise_word(t["text"]) for t in word_timings]

    # Greedy sequential match: walk through flat_words, find matching timing
    mapping = []
    t = 0
    for fn in flat_norm:
        if not fn:
            mapping.append(None)
            continue
        while t < len(timing_norm):
            if timing_norm[t] == fn:
                mapping.append(t)
                t += 1
                break
            t += 1
        else:
            return None

    # Build per-segment output
    result = []
    idx = 0
    last_reveal = 0.0
    for seg_words in seg_word_lists:
        seg_start = None
        seg_end = None
        words_out = []
        for orig_word in seg_words:
            m = mapping[idx]
            idx += 1
            if m is None:
                words_out.append({"text": orig_word, "reveal": last_reveal, "_skip": True})
                continue
            tw = word_timings[m]
            if seg_start is None:
                seg_start = tw["start"]
            seg_end = tw["end"]
            reveal = tw["start"] - seg_start
            last_reveal = reveal
            words_out.append({"text": tw["text"], "reveal": reveal})
        if seg_start is None:
            return None
        result.append({
            "words": words_out,
            "start": seg_start,
            "end": seg_end,
            "duration": seg_end - seg_start,
        })
    return result


def compute_timeline_from_words(segments, word_timings,
                                min_duration: float = DEFAULT_MIN_DURATION,
                                audio_duration: float | None = None):
    """Timeline derived from actual word timestamps instead of word counts.

    Each segment spans from its own first word to the *next* segment's first
    word, so inter-sentence pauses are covered on screen.  The last segment
    is extended to *audio_duration* to absorb any trailing silence.
    """
    matched = match_words_to_timings(segments, word_timings)
    if matched is None:
        audio_dur = audio_duration or (word_timings[-1]["end"] if word_timings else 0)
        return compute_timeline(segments, audio_dur, min_duration)

    timeline = []
    for i, m in enumerate(matched):
        start = m["start"]
        if i + 1 < len(matched):
            end = matched[i + 1]["start"]
        elif audio_duration is not None:
            end = audio_duration
        else:
            end = m["end"]
        dur = end - start
        timeline.append((start, end, dur))

    return timeline


def ffprobe_duration(path: Path) -> float:
    """Duration of a media file in seconds."""
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nokey=1:noprint_wrappers=1", str(path)],
        capture_output=True, text=True, check=True,
    )
    return float(out.stdout.strip())


def compute_durations(segments, audio_duration: float,
                      min_duration: float = DEFAULT_MIN_DURATION):
    """Seconds each segment's image is on screen, summing to audio_duration."""
    word_counts = [max(len(s["text"].split()), 1) for s in segments]
    total_words = sum(word_counts)

    durations = [max(min_duration, audio_duration * wc / total_words) for wc in word_counts]
    # Applying the floor inflates the total, so renormalize back onto the audio.
    scale = audio_duration / sum(durations)
    return [d * scale for d in durations]


def compute_timeline(segments, audio_duration: float,
                     min_duration: float = DEFAULT_MIN_DURATION):
    """List of (start, end, duration) per segment, in seconds."""
    durations = compute_durations(segments, audio_duration, min_duration)
    timeline = []
    cursor = 0.0
    for dur in durations:
        timeline.append((cursor, cursor + dur, dur))
        cursor += dur
    return timeline


def frame_spans(timeline, fps: int):
    """Whole-frame span per segment as (first_frame, frame_count).

    Rounding each boundary to the nearest frame (rather than rounding each
    duration independently) guarantees the segments tile the timeline with no
    gaps or overlaps, so the stills track and the subtitles track end up with
    identical frame counts and stay locked together.
    """
    spans = []
    for start, end, _ in timeline:
        first = int(round(start * fps))
        last = int(round(end * fps))
        spans.append((first, max(last - first, 1)))
    return spans


def smoothstep(t: float) -> float:
    """Ease in and out, with zero velocity at both ends.

    Used for the Ken Burns zoom: a linear ramp visibly starts and stops dead,
    and back-to-back segments read as a mechanical jerk at the cut.
    """
    t = min(max(t, 0.0), 1.0)
    return t * t * (3.0 - 2.0 * t)
